# Generated by Django 6.1.1 on 2026-09-27 22:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('timezone', models.CharField(default='America/New_York', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='operations.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.order')),
            ],
        ),
        migrations.CreateModel(
            name='PreparedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('unit', models.CharField(choices=[('ml', 'Milliliter'), ('g', 'Gram'), ('serving', 'Serving')], max_length=20)),
                ('default_shelf_life', models.DurationField()),
                ('default_batch_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('usage_buffer_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_items', to='operations.shop')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='operations.shop'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='operations.shop'),
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location_type', models.CharField(choices=[('refrigerator', 'Refrigerator'), ('freezer', 'Freezer'), ('room_temperature', 'Room Temperature'), ('prep_station', 'Prep Station')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='operations.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('cooling', 'Cooling'), ('ready', 'Ready'), ('depleted', 'Depleted'), ('expired', 'Expired'), ('discarded', 'Discarded')], default='preparing', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prepared_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='operations.prepareditem')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='operations.storagelocation')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('batch_created', 'Batch Created'), ('order_consumption', 'Order Consumption'), ('waste', 'Waste'), ('correction', 'Correction'), ('expiry', 'Expiry')], max_length=30)),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_events', to='operations.batch')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_events', to='operations.orderitem')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['batch', 'created_at'], name='operations__batch_i_7cd66f_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_components', to='operations.menuitem')),
                ('prepared_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_components', to='operations.prepareditem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('menu_item', 'prepared_item'), name='unique_prepared_item_per_recipe')],
            },
        ),
        migrations.AddConstraint(
            model_name='prepareditem',
            constraint=models.UniqueConstraint(fields=('shop', 'name'), name='unique_prepared_item_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('shop', 'name'), name='unique_menu_item_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='storagelocation',
            constraint=models.UniqueConstraint(fields=('shop', 'name'), name='unique_storage_location_per_shop'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['prepared_item', 'status', 'expires_at'], name='operations__prepare_f85d98_idx'),
        ),
    ]
