# Generated by Django 6.1.1 on 2026-09-27 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ice_level',
            field=models.CharField(choices=[('no_ice', 'No Ice'), ('less_ice', 'Less Ice'), ('regular_ice', 'Regular Ice'), ('extra_ice', 'Extra Ice')], default='regular_ice', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sugar_level',
            field=models.CharField(choices=[('0', '0%'), ('25', '25%'), ('50', '50%'), ('75', '75%'), ('100', '100%')], default='100', max_length=3),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='operations.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='OrderItemTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='operations.orderitem')),
                ('prepared_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item_toppings', to='operations.prepareditem')),
            ],
        ),
    ]
