# Generated by Django 6.1.1 on 2026-09-29 20:55

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_orderitem_ice_level_orderitem_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepareditem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='prepareditem',
            name='usage_buffer_percent',
        ),
        migrations.AddField(
            model_name='batch',
            name='initial_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prepareditem',
            name='base_unit',
            field=models.CharField(choices=[('ml', 'Milliliter'), ('g', 'Gram'), ('oz', 'Ounce')], default='g', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prepareditem',
            name='batch_label',
            field=models.CharField(default='batch', max_length=30),
        ),
        migrations.AddField(
            model_name='prepareditem',
            name='preparation_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prepareditem',
            name='quantity_per_serving',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='inventory_buffer_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='shop',
            name='low_stock_threshold_servings',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
