# Generated by Django 6.1.1 on 2026-10-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_remove_prepareditem_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepareditem',
            name='requires_cooling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
